### PR TITLE
function added "scroll-button"

### PR DESCRIPTION
**Pull request by Padmanabh82**

### CODE REVIEW

**Comment by Padmanabh82** [comment]
Don't merge it. It is my old code

**Comment by Padmanabh82** [comment]
Why is my code failed in test ??

**Comment by Padmanabh82** [comment]
Don't commit it I am working on it

**Comment by Padmanabh82** [comment]
i have tried my best and made it done and it passed all steps

**Review by ShamikG17 — APPROVED** [review]
approved

**Pull request merged**
