### PR TITLE
Footer

### PR DESCRIPTION
**Pull request by Padmanabh82**

### CODE REVIEW

**Comment by Padmanabh82** [comment]
It was because I edited it from mobile because I had code but computer was not available wait I will update it

**Comment by Padmanabh82** [comment]
The sand box link where I coded :- https://codesandbox.io/s/frosty-oskar-ww44o?file=/src/pages/Home.js

**Comment by Padmanabh82** [comment]
On mobile

**Comment by Padmanabh82** [comment]
its working fine on my computer but why it cannot pass test

**Comment by ShamikG17** [comment]
Greetings @Padmanabh82 , you are requested to not make any PRs unless and untill you are assigned to the issue. Please abide by these rules.

**Comment by Padmanabh82** [comment]
Ok sir sorry I didn't know it

**Pull request closed without merging**
