### PR TITLE
added footer component to the react app

### PR DESCRIPTION
**Pull request by Atharvamaid**
image
#2

### CODE REVIEW

**Review by ShamikG17 — APPROVED** [review]
approved

**Comment by Atharvamaid** [comment]
> approved

Hey @ShamikG17 could tell me why the checks were failed when I created the pr ?

**Comment by ShamikG17** [comment]
@Atharvamaid my bad, I didn't check the deploy logs. You will have to get rid of all warnings that appear during compiling. I am attaching the screenshot of the warnings. Can you clear the warnings and make a PR again?
image

**Comment by Atharvamaid** [comment]
> @Atharvamaid my bad, I didn't check the deploy logs. You will have to get rid of all warnings that appear during compiling. I am attaching the screenshot of the warnings. Can you clear the warnings and make a PR again? image
sure I will do that

**Pull request merged**
